packages:
  - apps/*
onlyBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  prisma: true
  sharp: true
  unrs-resolver: true
